kind: KedaController
apiVersion: keda.sh/v1alpha1
metadata:
  name: keda
  namespace: openshift-keda
spec:
  watchNamespace: 'quotes'
  operator:
    logLevel: info 
    logEncoder: console 
  metricsServer:
    logLevel: '0' 
  serviceAccount: {}